# Task 1: Read and Aggregate Gym Usage Data
1. Use pandas to read the "hietaniemi-gym-data.csv" file into a DataFrame.
2. Convert the timestamps to datetime objects.
3. Aggregate the data to hourly precision by summing the usage statistics for each gym device during the hour.
4. Present the first 10 rows of the aggregated dataset.

In [37]:
import pandas as pd
import plotly as plt
import plotly.express as px

In [38]:
df_gym = pd.read_csv("hietaniemi-gym-data.csv")
df_gym.head()

                        time  19  20  21  22  23  24  25  26
0  2020-04-24 00:00:00+00:00   2   2   2   2   2   2   2   2
1  2020-04-24 00:10:00+00:00   2   2   2   2   2   2   2   2
2  2020-04-24 00:20:00+00:00   2   2   2   2   2   2   2   2
3  2020-04-24 00:30:00+00:00   2   2   2   2   2   2   2   2
4  2020-04-24 00:40:00+00:00   2   2   2   2   2   2   2   2

In [27]:
df_weather = pd.read_csv("kaisaniemi-weather-data.csv")
df_weather.head()

,Year,Month,Day,Hour,Timezone,Precipitation (mm),Snow depth (cm),Temperature (degC)
0,2020,4,24,00:00,UTC,0.0,0.0,6.2
1,2020,4,24,01:00,UTC,0.0,0.0,6.2
2,2020,4,24,02:00,UTC,0.0,0.0,5.1
3,2020,4,24,03:00,UTC,0.0,0.0,4.6
4,2020,4,24,04:00,UTC,0.0,0.0,4.7

In [39]:
df_gym = df_gym.rename(columns= {"19": "etupenkki", "20": "ojentajapunnerrus", "21": "vinopenkkipunnerrus", "22": "hauiskääntö", "23": "penkkipunnerrus", "24": "ylöveto", "25": "jalkakyykky", "26": "soutulaite"})
df_gym.head()

,time,etupenkki,ojentajapunnerrus,vinopenkkipunnerrus,hauiskääntö,penkkipunnerrus,ylöveto,jalkakyykky,soutulaite
0,2020-04-24 00:00:00+00:00,2,2,2,2,2,2,2,2
1,2020-04-24 00:10:00+00:00,2,2,2,2,2,2,2,2
2,2020-04-24 00:20:00+00:00,2,2,2,2,2,2,2,2
3,2020-04-24 00:30:00+00:00,2,2,2,2,2,2,2,2
4,2020-04-24 00:40:00+00:00,2,2,2,2,2,2,2,2

In [40]:
# Step 2: Convert the timestamps to datetime objects
df_gym['time'] = pd.to_datetime(df_gym['time'])

# Step 3: Extract the hour from the timestamp
df_gym['hour'] = df_gym['time'].dt.floor('H')

# Step 4: Aggregate the data by hour, summing the numerical columns
agg_df = df_gym.groupby(['hour']).sum().reset_index()

# Step 5: Present the first 10 rows of the aggregated dataset
print(agg_df.head(10))

/var/folders/72/q42hyhx16xj2zjy00d3ks2yh0000gn/T/ipykernel_6608/2745305376.py:5: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df_gym['hour'] = df_gym['time'].dt.floor('H')

TypeError: datetime64 type does not support sum operations

In [30]:
# Convert time column into datatime objects
df_gym['time'] = pd.to_datetime(df_gym['time'])

In [34]:
df_gym['hour'] = df_gym['time'].dt.floor('H')  # Extract the hour from the timestamp

/var/folders/72/q42hyhx16xj2zjy00d3ks2yh0000gn/T/ipykernel_6608/3776957410.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df_gym['hour'] = df_gym['time'].dt.floor('H')  # Extract the hour from the timestamp

In [36]:
agg_df = df_gym.groupby(['hour']).sum().reset_index()

TypeError: datetime64 type does not support sum operations

In [35]:
df_gym.head()

,time,etupenkki,ojentajapunnerrus,vinopenkkipunnerrus,hauiskääntö,penkkipunnerrus,ylöveto,jalkakyykky,soutulaite,hour
0,2020-04-24 00:00:00+00:00,2,2,2,2,2,2,2,2,2020-04-24 00:00:00+00:00
1,2020-04-24 00:10:00+00:00,2,2,2,2,2,2,2,2,2020-04-24 00:00:00+00:00
2,2020-04-24 00:20:00+00:00,2,2,2,2,2,2,2,2,2020-04-24 00:00:00+00:00
3,2020-04-24 00:30:00+00:00,2,2,2,2,2,2,2,2,2020-04-24 00:00:00+00:00
4,2020-04-24 00:40:00+00:00,2,2,2,2,2,2,2,2,2020-04-24 00:00:00+00:00

In [33]:
df_gym.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55102 entries, 0 to 55101
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   time                 55102 non-null  datetime64[ns, UTC]
 1   etupenkki            55102 non-null  int64
 2   ojentajapunnerrus    55102 non-null  int64
 3   vinopenkkipunnerrus  55102 non-null  int64
 4   hauiskääntö          55102 non-null  int64
 5   penkkipunnerrus      55102 non-null  int64
 6   ylöveto              55102 non-null  int64
 7   jalkakyykky          55102 non-null  int64
 8   soutulaite           55102 non-null  int64
dtypes: datetime64[ns, UTC](1), int64(8)
memory usage: 3.8 MB

In [21]:
import pickle

# Open the .pkl file in read-binary mode
with open('model.pkl', 'rb') as f:
    # Load the object from the file
    data = pickle.load(f)

# Now, 'data' contains the deserialized object from the .pkl file

In [23]:
print(data)

['weekday' 'hour' 'Precipitation (mm)' 'Snow depth (cm)'
 'Temperature (degC)']

In [43]:
import pandas as pd
import pickle

# Task 1: Read the CSV file and aggregate the data to hourly precision
df = pd.read_csv('hietaniemi-gym-data.csv', parse_dates=['time'], index_col='time')
hourly_aggregated = df.resample('H').sum()

# Task 2: Check number of rows, date range, and if all numerical values are positive
num_rows = hourly_aggregated.shape[0]
date_range = (hourly_aggregated.index.min(), hourly_aggregated.index.max())
all_positive = (hourly_aggregated >= 0).all().all()

# Task 3: Find the most popular device, analyze time of day, and day of week
most_popular_device = hourly_aggregated.sum().idxmax()
hourly_aggregated['hour'] = hourly_aggregated.index.hour
hourly_aggregated['day_of_week'] = hourly_aggregated.index.dayofweek
time_of_day_analysis = hourly_aggregated.groupby('hour').sum()
day_of_week_analysis = hourly_aggregated.groupby('day_of_week').sum()

# Task 4: Extract weekday and hour, and calculate sum of minutes
hourly_aggregated['weekday'] = hourly_aggregated.index.weekday
hourly_aggregated['hour_of_day'] = hourly_aggregated.index.hour
sum_of_minutes = hourly_aggregated['25'].sum()

# Task 5: Read weather data and merge with gym data for analysis
weather_df = pd.read_csv('kaisaniemi-weather-data.csv')  # assuming weather data is stored in 'kaisaniemi-weather-data.csv'
merged_data = hourly_aggregated.merge(weather_df, left_index=True, right_index=True)

# Bonus Task: Load model and make predictions
with open("model.pkl", "rb") as f:
    model = pickle.load(f)  # assuming the model is saved as 'model.pkl'

# Ensure that the loaded model has a 'predict' method
if hasattr(model, 'predict'):
    predictions = model.predict(merged_data)
else:
    print("Error: Loaded model does not have a 'predict' method.")

# Display results
print("Task 1: Hourly Aggregated Data")
print(hourly_aggregated.head())
print("\nTask 2: Number of Rows, Date Range, All Values Positive")
print("Number of Rows:", num_rows)
print("Date Range:", date_range)
print("All Values Positive:", all_positive)
print("\nTask 3: Most Popular Device, Time of Day Analysis, Day of Week Analysis")
print("Most Popular Device:", most_popular_device)
print("Time of Day Analysis:")
print(time_of_day_analysis)
print("Day of Week Analysis:")
print(day_of_week_analysis)
print("\nTask 4: Sum of Minutes")
print("Sum of Minutes:", sum_of_minutes)
print("\nTask 5: Merged Data with Weather")
print(merged_data.head())
if hasattr(model, 'predict'):
    print("\nBonus Task: Predictions using Loaded Model")
    print("Predictions:")
    print(predictions)

Error: Loaded model does not have a 'predict' method.
Task 1: Hourly Aggregated Data
                           19  20  21  22  23  24  25  26  hour  day_of_week  \
time
2020-04-24 00:00:00+00:00  12  12  12  12  12  12  12  12     0            4
2020-04-24 01:00:00+00:00  12  12  12  12  12  12  12  12     1            4
2020-04-24 02:00:00+00:00  12  12  12  14  12  13  12  13     2            4
2020-04-24 03:00:00+00:00  13  14  15  12  18  20  23  20     3            4
2020-04-24 04:00:00+00:00  24  15  23  24  19  25  30  28     4            4

                           weekday  hour_of_day
time
2020-04-24 00:00:00+00:00        4            0
2020-04-24 01:00:00+00:00        4            1
2020-04-24 02:00:00+00:00        4            2
2020-04-24 03:00:00+00:00        4            3
2020-04-24 04:00:00+00:00        4            4

Task 2: Number of Rows, Date Range, All Values Positive
Number of Rows: 9184
Date Range: (Timestamp('2020-04-24 00:00:00+0000', tz='UTC'), Timestamp('2021-05-11 15:00:00+0000', tz='UTC'))
All Values Positive: True

Task 3: Most Popular Device, Time of Day Analysis, Day of Week Analysis
Most Popular Device: 25
Time of Day Analysis:
         19    20     21    22     23    24     25    26  day_of_week
hour
0      4607  4609   4613  4606   4616  4603   4614  4598         1150
1      4656  4604   4700  4604   4680  4597   4705  4598         1150
2      4706  4658   4712  4627   4817  4641   4757  4637         1150
3      4961  4976   5043  4906   5081  4936   5058  4916         1150
4      5895  5514   5771  5481   6164  5541   6349  5556         1150
5      6368  5972   6106  5884   6417  5839   6960  5847         1150
6      6945  6323   6769  6248   6967  6234   7659  6055         1150
7      7806  7161   7442  6870   7953  6825   8362  6631         1150
8      8769  7791   8286  7861   8697  7118   9256  7018         1150
9      9090  8012   8737  8141   9060  7330   9637  7301         1150
10     8910  8514   8793  8106   9055  7274   9698  7062         1150
11     8839  8451   8801  8149   9173  7321   9621  7017         1150
12     8965  8525   8895  8197   9282  7097   9962  7089         1150
13     9473  8663   9199  8500   9749  7361  10449  7667         1150
14    10086  9435   9825  9047  10176  8020  10930  8196         1150
15    10348  9633  10004  9349  10278  8152  11355  8113         1150
16     9969  9549   9719  9135  10078  7870  10792  8038         1149
17     8837  8442   8770  8027   8969  7020   9772  7214         1149
18     7106  6851   7044  6563   7440  6143   7728  6043         1149
19     5490  5504   5357  5336   5786  5250   5730  5100         1149
20     4907  5017   4912  4900   5076  4869   5064  4774         1149
21     4702  4741   4707  4680   4724  4657   4762  4652         1149
22     4673  4632   4635  4629   4671  4619   4710  4610         1149
23     4607  4600   4603  4590   4607  4591   4602  4591         1149
Day of Week Analysis:
                19     20     21     22     23     24     25     26   hour
day_of_week
0            25404  23750  24848  23098  25956  21488  27377  21636  15180
1            24946  23726  24305  23247  25444  21427  26633  21389  15024
2            24378  23233  23895  22850  24980  21249  26181  21200  14904
3            23866  22645  23499  22333  24385  20891  25727  20982  14904
4            24036  22470  23462  22263  24151  21351  25569  21091  15180
5            23667  22728  23279  21740  23804  20250  25096  20101  15180
6            24418  23625  24155  22905  24796  21252  25949  20924  15180

Task 4: Sum of Minutes
Sum of Minutes: 182532

Task 5: Merged Data with Weather
Empty DataFrame
Columns: [19, 20, 21, 22, 23, 24, 25, 26, hour, day_of_week, weekday, hour_of_day, Year, Month, Day, Hour, Timezone, Precipitation (mm), Snow depth (cm), Temperature (degC)]
Index: []

/var/folders/72/q42hyhx16xj2zjy00d3ks2yh0000gn/T/ipykernel_6608/775277247.py:6: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly_aggregated = df.resample('H').sum()